## 어제 문제풀이


```python
# 동건님 코드 : 문제는 없으나 add를 실행시키긴 해야합니다!
# 데코레이터 => 아래 코드는 데코할 대상이 없는거에요.

'''
추가로 부연 설명을 합니다. :)
스토리로 굳이 표현하자면 아래와 같습니다.

1. add라는 함수를 내가 1년 전에 만들었다. 문제 없이 잘 작동하는 함수이다.
2. 이 add를 데코레이터를 써서 파일 입출력이 되게 하고 싶다.
3. 데코레이터를 만든다.
4. 기존의 코드도 정상적으로 작동이 되어야 한다.
'''

import json

def writerfile(func):
    def wrapper(a, b):
        data1 = ['a', 'b', 'a+b']
        data2 = [a, b, a+b]
        f = open('writerfile.json', 'w')
        json.dump(dict(zip(data1,data2)), f, indent = 4)
        f.close()
    return wrapper

@writerfile
def add(a,b):
    return a + b

add(10, 20)
```


```python
# 기존 코드
def add(a,b):
    return a + b

result = add(10, 20) + add(10, 20)
print(result)
```


```python
import json

def writerfile(func):
    def wrapper(a, b):
        data1 = ['a', 'b', 'a+b']
        data2 = [a, b, a+b]
        f = open('writerfile.json', 'w')
        json.dump(dict(zip(data1,data2)), f, indent = 4)
        f.close()
        return func(a, b)
    return wrapper

@writerfile
def add(a,b):
    return a + b

result = add(10, 20) + add(10, 20)
print(result)
```

## 파일 내용 추가


```python
f = open('python.txt', 'w')
s = ''
for i in range(5):
    s += f'{i}명 참여 중입니다. \n'
f.write(s)
f.close()
```


```python
f = open('python.txt', 'a') # 다시 write 모드로 하면 처음부터 덮어 씁니다.
s = ''
for i in range(5, 11):
    s += f'{i}명 참여 중입니다. \n'
f.write(s)
f.close()
```

* 파일이 계속 열려있는 상태가 유지
* 메모리 효율

## 파일 열기와 닫기를 동시에


```python
with open('test.txt', 'w') as f:
    f.write('Life is too short, you need python')
```

## Python Error

* Python에서는 에러를 만나면 코드가 (서비스가) 멈춘다.
* 내가 짠 코드가 서비스에 영향이 끼쳐지지 않도록 시니어분들이 견고한 코드를 작성 해놨을것이다.
* TDD, 테스트 주도 개발 등 Test를 할 수 있는 환경이 갖춰져 있다.
* 작성한 코드는 실서비스로 바로 배포 되지 않는다.작성한 코드는 테스트 서버로 일단 배포 이후 잘 작동하는지 테스트 해본다.


```python
# SyntaxError

for i in range(10)  # : 가 빠져있어서 나는 에러
    print(i)
```


```python
# Name Error
print(x) # x가 정의 되지않았을때
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-2-6d755674e41b> in <cell line: 2>()
          1 # Name Error
    ----> 2 print(x) # x가 정으 되지않았을때
    

    NameError: name 'x' is not defined



```python
# Type Error
x = 10
y = '20'
print(x+y)
```


    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    <ipython-input-3-e0559a0a2e0c> in <cell line: 4>()
          2 x = 10
          3 y = '20'
    ----> 4 print(x+y)
    

    TypeError: unsupported operand type(s) for +: 'int' and 'str'



```python
# Index Error
my_list = [1, 2, 3]
print(my_list[3])
```


    ---------------------------------------------------------------------------

    IndexError                                Traceback (most recent call last)

    <ipython-input-5-f79f21f7e49e> in <cell line: 3>()
          1 # Index Error
          2 my_list = [1, 2, 3]
    ----> 3 print(my_list[3])
    

    IndexError: list index out of range



```python
# Key Error
my_dict = {'a' : 1, 'b': 2}
print(my_dict['c'])
```


    ---------------------------------------------------------------------------

    KeyError                                  Traceback (most recent call last)

    <ipython-input-6-9f7ff5b950ab> in <cell line: 3>()
          1 # Key Error
          2 my_dict = {'a' : 1, 'b': 2}
    ----> 3 print(my_dict['c'])
    

    KeyError: 'c'



```python
# Value Error
int('a')
```


    ---------------------------------------------------------------------------

    ValueError                                Traceback (most recent call last)

    <ipython-input-7-b8f9f0574b88> in <cell line: 2>()
          1 # Value Error
    ----> 2 int('a')
    

    ValueError: invalid literal for int() with base 10: 'a'



```python
# Attribute Error
my_list = [1, 2, 3]
print(my_list.appeend(4))
```


    ---------------------------------------------------------------------------

    AttributeError                            Traceback (most recent call last)

    <ipython-input-8-dceecff01ea8> in <cell line: 3>()
          1 # Attribute Error
          2 my_list = [1, 2, 3]
    ----> 3 print(my_list.appeend(4))
    

    AttributeError: 'list' object has no attribute 'appeend'



```python
# Type Error
def add(x, y):
    return x + y

add(1, 2, 3)
```

## 예외 처리


```python
try:
    # 예외가 발생할 가능성이 있는 코드
except:
    # 예외 처리코드
```


      File "<ipython-input-9-f0a7f7382797>", line 3
        except:
        ^
    IndentationError: expected an indented block after 'try' statement on line 1




```python
def div(a,b):
    return a / b

try:
    return div(1,0)
except:
    print('예외발생')
```


      File "<ipython-input-12-e9f97d98fef8>", line 5
        return div(1,0)
        ^
    SyntaxError: 'return' outside function




```python
def div(a,b):
    return a / b

try:
    div(1,0)
except:
    print('예외발생')

result = f() + f() # result에는 float값이 나오길 기대한다.
print(result)
```

    예외발생



    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    <ipython-input-11-bc34937dd1fb> in <cell line: 9>()
          7     print('예외발생')
          8 
    ----> 9 result = f() + f() # result에는 float값이 나오길 기대한다.
         10 print(result)


    TypeError: '_io.TextIOWrapper' object is not callable



```python
def div(a, b):
    return a / b

def f():
    try:
        return div(1, 0)
    except:
        return float('inf')

result = f() + f() #result에는 float이 오길 기대하죠.
print(result)
```

    inf



```python
def div(a, b):
    return a / b

def f():
    try:
        return div(1, 0)
    except:
        return None

result = f() + f() #result에는 float이 오길 기대하죠.
print(result)
```


    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    <ipython-input-14-6c7844611608> in <cell line: 10>()
          8         return None
          9 
    ---> 10 result = f() + f() #result에는 float이 오길 기대하죠.
         11 print(result)


    TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'



```python
def div(a, b):
    return a / b

def f():
    try:
        return div(1, 0)
    except:
        return 0

result = f() + f() #result에는 float이 오길 기대하죠.
print(result)
```


```python
try:
    # 예외가 발생할 가능성이 있는 코드
except:
    # 예외 처리 코드
else:
    # 예외가 발생하지 않을 때 실행되는 코드
```


```python
try:
    1/0
except:
    print('예외 발생!')
else:
    print('정상 종료!')
```


```python
# while, for, try-except 구문에서 else는 언제 실행?
# 정상 종료 될때
```


```python
try:
    10/2
except:
    print('예외발생')
else:
    print('정상 종료')
```

    정상 종료



```python
# error가 나면 코드가 멈추기 때문에 보통 except와 함께 사용합니다.
try:
    # 예외가 발생할 가능성이 있는 코드
finally:
    # 예외 발생 여부와 상관없이 항상 실행되는 코드
```


```python
try:
    1/0
finally:
    print('finally')

print('hello world')
```


```python
try:
    # 예외가 발생할 가능성이 있는 코드
except:
    # 예외 처리 코드
finally:
    # 예외 발생 여부와 상관없이 항상 실행되는 코드
```


```python
try:
    1/0
except:
    print('hello')
finally:
    print('world')
```


```python
try:
    # 예외가 발생할 가능성이 있는 코드
except:
    # 예외 처리 코드
else:
    # 예외가 발생하지 않을 때 실행되는 코드
finally:
    # 예외 발생 여부와 상관없이 항상 실행되는 코드
```


```python
try:
    1/0
except:
    print('except')
else:
    print('else')
finally:
    print('finally')
```


```python
try:
    10/2
except:
    print('except')
else:
    print('else')
finally:
    print('finally')
```


```python
raise
```


```python
# raise 애러이름
raise ValueError
```


```python
raise LeeHoJun
```


```python
raise ValueError('코드를 잘~~ 만들어주세요.')
```


```python
try:
    1/0
except ValueError:
    print('ValueError')
except ZeroDivisionError:
    print('ZeroDivisionError')

print(ZeroDivisionError)
print(type(ZeroDivisionError))
print(dir(ZeroDivisionError))
```


```python
class Leehojun(Exception): #Exception을 상속받으면 됩니다.
    def __init__(self):
        super().__init__('입력된 값이 leehojun이 아닙니다.')

if 'leehojun' != input():
    raise Leehojun
else:
    print('leehojun이 맞습니다!')
```


```python
!pip list
```


```python

```


```python
import sys

sys.path
```

## 기초역량 테스트


```python
# 1번
#원주율 정수(3)만 출력하도록 코드를 짜보세요.

원주율 = 3.141592


print(int(원주율))
```

    3



```python
# 2번
# 다음 파이썬 문법 중에서 True로 사용하는 것을 고르시오.
# 1. None
# 2. 1
# 3. ""
# 4. 0
# 5. bool(0)
# 정답 2
```


```python
# 3번
#인사말을 완성해주세요

my_name = input('이름')

print(f'안녕하세요 {my_name}입니다.')
```

    이름홍길동
    안녕하세요 홍길동입니다.



```python
# 4번
# 리스트 요소 삭제 방법으로 맞지 않는 것은?
# 1. del 구문
# 2. clear()
# 3. reverse()
# 4. remove()
# 5. pop()

# 정답 3번
```


```python
# 5번
# 숫자를 입력 받고, 해당 값의 약수를 구하는 함수를 작성하시오
num = int(input())

def divisor(num):
    data = []
    for i in range(1, num + 1):
        if num % i == 0:
            data.append(i)
        return data
        

divisor(num)
```

    10





    [1]




```python
# 6번
# 함수는 리스트와 알파벳을 입력받습니다. 
# 입력받은 리스트에서 알파벳이 몇 개 있는지 출력하는 함수를 만들어주세요.
def solution(l, a):
    return  l.count(a)

solution(['a', 'b', 'c', 'a', 'a'], 'a') # 정답 : 3

```




    3




```python
# 7번
# 함수는 2차원 리스트를 입력받습니다. 
# 아래와 같이 2차원 리스트를 두번째 값을 기준으로 내림차순 정렬하는 함수를 만들어주세요.

def solution(l):
    return sorted(l, key=lambda x:x[1], reverse = True)
         

solution([[10, 5], [20, 3], [30, 4], [40, 1]]) 
# 정답 : [[10, 5], [30, 4], [20, 3], [40, 1]]
```




    [[10, 5], [30, 4], [20, 3], [40, 1]]




```python
# 8번
# 2차원 리스트가 주어졌을 때 각 값의 차를 저장한 리스트를 출력해주세요.
def solution(l):
    return list(map(lambda x:x[0]-x[1] ,l))

solution([[10, 5], [20, 3], [30, 4], [40, 1]]) 
# 정답 : [[5], [17], [26], [39]]
```




    [5, 17, 26, 39]




```python
# 9번
# 주어진 문자열의 합을 구하는 코드를 작성하세요.
def solution(s):
    return sum(map(int,list(s)))

solution('11123') 
# 정답 : 8
```




    8




```python
# 10번
# 주어진 문자열에서 ‘!’와 공백을 없애는 코드를 작성하세요.
def solution(s):
    return s.replace(' ','').replace('!','')

solution('!hello!wor     ld!     ') 
# 정답 : helloworld
```




    'helloworld'



## 클로저, 팩토리 함수


```python
def one():
    def two():
        return
    return two

hello == one() # hello == two
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-45-0001dfe652a1> in <cell line: 6>()
          4     return two
          5 
    ----> 6 hello == one() # hello == two
    

    NameError: name 'hello' is not defined



```python
def one(x):
    def two():
        return x + x
    return two

hello ==  one(10) # hello == two
hello() # hello() = two
```


```python
def one(x):
    def two(a, b):
        return a + b + x
    return two

hello = one(10) # hello == two
hello(2, 3) # hello() == two()
```


```python
def user(username, usermoney):
    def userbuy(productname, productprice):
        leftmoney = usermoney - productprice
        return f'{productname}를 {username}님이 구매하셔서 계좌에 {leftmoney}가 남아있습니다.'
    return userbuy

이호준구매 = user('leehojun', 1000000)
이호준구매('자전거', 100000)

홍길동구매 = user('hongildong', 1000000)
홍길동구매('킥보드', 50000)

# 이호준구매와 홍길동구매 함수를 가지고 계좌를 조작할 수 있나요?
# 계좌 변수에 접근할 수 있나요?
```


```python
# S은행에 입사를 했습니다. 여러분들의 권한은 이호준구매 등에 구매함수만 조작할 수 있습니다
# 이렇게 되면 계좌 정보를 접근할 수가 없겠죠?
# 접근 통제, 제한, 변수 보호 등으로 사용합니다.
```
